from app.models.opportunity import Opportunity, OpportunityType
from typing import Optional
from datetime import date


class OpportunityStore:
    SEED_OPPORTUNITIES = [
        Opportunity(
            id="seed_001",
            title="Gates Millennium Scholars Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Bill & Melinda Gates Foundation",
            amount="$20,000/year",
            deadline=date(2026, 9, 15),
            url="https://www.gmsp.org",
            description="Full scholarship for outstanding minority students with financial need",
            requirements=["US Citizen or Permanent Resident", "Minimum 3.3 GPA", "Demonstrated leadership", "Financial need"],
            citizenship_requirements=["US Citizen", "Permanent Resident"],
            gpa_requirement=3.3,
            degree_levels=["Bachelor", "Master", "PhD"],
            fields_of_study=["Computer Science", "Engineering", "Mathematics", "Science", "Education", "Public Health"],
            skills_required=["Leadership", "Community Service"],
            tags=["full_ride", "minority", "leadership", "financial_need"],
        ),
        Opportunity(
            id="seed_002",
            title="International Student Scholar Award",
            type=OpportunityType.SCHOLARSHIP,
            organization="Global Education Foundation",
            amount="$10,000/semester",
            deadline=date(2026, 10, 1),
            url="https://www.globaledfoundation.org/scholarships",
            description="Scholarship for international students demonstrating academic excellence",
            requirements=["International student status", "Minimum 3.5 GPA", "Full-time enrollment", "English proficiency"],
            citizenship_requirements=["International"],
            gpa_requirement=3.5,
            degree_levels=["Bachelor", "Master"],
            fields_of_study=["Computer Science", "Engineering", "Business", "Arts", "Sciences"],
            skills_required=["Academic Excellence"],
            tags=["international", "academic_excellence"],
        ),
        Opportunity(
            id="seed_003",
            title="SWE Google Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Google",
            amount="$9,000/month",
            deadline=date(2026, 11, 1),
            url="https://careers.google.com/internships",
            description="Software engineering internship at Google working on production systems",
            requirements=["Currently pursuing CS or related degree", "Strong DSA skills", "Returning to degree program after internship"],
            gpa_requirement=3.0,
            degree_levels=["Bachelor", "Master", "PhD"],
            fields_of_study=["Computer Science", "Software Engineering", "Data Science"],
            skills_required=["Python", "Java", "Algorithms", "Data Structures", "Problem Solving"],
            tags=["tech", "software", "top_company"],
        ),
        Opportunity(
            id="seed_004",
            title="Microsoft Explore Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Microsoft",
            amount="$8,500/month",
            deadline=date(2026, 10, 15),
            url="https://careers.microsoft.com/students/internships",
            description="First and second year undergraduate internship program for CS students",
            requirements=["First or second year undergraduate", "Enrolled in CS or related field", "US work authorization"],
            citizenship_requirements=["US Citizen", "Permanent Resident"],
            degree_levels=["Bachelor"],
            fields_of_study=["Computer Science", "Computer Engineering", "Data Science", "Information Technology"],
            skills_required=["C#", "Python", "Problem Solving", "Communication"],
            tags=["early_career", "tech", "undergraduate"],
        ),
        Opportunity(
            id="seed_005",
            title="Fulbright Foreign Student Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Bureau of Educational and Cultural Affairs",
            amount="Full tuition + living stipend",
            deadline=date(2026, 5, 1),
            url="https://foreign.fulbrightonline.org",
            description="Full scholarship for international students to study in the US",
            requirements=["International student", "Bachelor's degree", "English proficiency", "Strong academic record"],
            citizenship_requirements=["International"],
            gpa_requirement=3.2,
            degree_levels=["Master", "PhD"],
            fields_of_study=["All fields"],
            skills_required=["Leadership", "Research", "Cultural Exchange"],
            tags=["international", "full_ride", "prestigious"],
        ),
        Opportunity(
            id="seed_006",
            title="Jane Street Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Jane Street Capital",
            amount="$16,000/month",
            deadline=date(2026, 9, 1),
            url="https://www.janestreet.com/join-jane-street/internships/",
            description="Quantitative trading and research internship",
            requirements=["Strong quantitative background", "Problem solving skills", "Interest in finance and technology"],
            gpa_requirement=3.5,
            degree_levels=["Bachelor", "Master", "PhD"],
            fields_of_study=["Computer Science", "Mathematics", "Physics", "Engineering", "Statistics"],
            skills_required=["Python", "Statistics", "Probability", "Problem Solving", "Quantitative Analysis"],
            tags=["quantitative", "finance", "high_pay"],
        ),
        Opportunity(
            id="seed_007",
            title="National Merit Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Merit Scholarship Corporation",
            amount="$2,500/year",
            deadline=date(2026, 3, 1),
            url="https://www.nationalmerit.org/scholarships",
            description="Scholarship for high-achieving students based on PSAT/NMSQT performance",
            requirements=["US Citizen or Permanent Resident", "High PSAT/NMSQT score", "Enrolled in high school or college"],
            citizenship_requirements=["US Citizen", "Permanent Resident"],
            gpa_requirement=3.5,
            degree_levels=["Bachelor"],
            fields_of_study=["All fields"],
            skills_required=["Academic Excellence"],
            tags=["merit", "undergraduate", "standardized_test"],
        ),
        Opportunity(
            id="seed_008",
            title="Research Internship at DeepMind",
            type=OpportunityType.INTERNSHIP,
            organization="Google DeepMind",
            amount="$11,000/month",
            deadline=date(2026, 12, 1),
            url="https://deepmind.com/careers/internships",
            description="Research internship in machine learning and AI",
            requirements=["PhD student in ML or related field", "Strong publication record", "Deep learning expertise"],
            degree_levels=["PhD"],
            fields_of_study=["Computer Science", "Machine Learning", "Artificial Intelligence", "Mathematics", "Neuroscience"],
            skills_required=["Python", "PyTorch", "TensorFlow", "Deep Learning", "Research", "Machine Learning"],
            tags=["ai", "research", "prestigious", "phd"],
        ),
        Opportunity(
            id="seed_009",
            title="IEEE Fellowship for Engineering Students",
            type=OpportunityType.SCHOLARSHIP,
            organization="IEEE",
            amount="$5,000/semester",
            deadline=date(2026, 6, 15),
            url="https://www.ieee.org/education/scholarships",
            description="Scholarship for outstanding engineering and computer science students",
            requirements=["IEEE member", "Engineering or CS major", "Minimum 3.0 GPA", "Research potential"],
            gpa_requirement=3.0,
            degree_levels=["Bachelor", "Master", "PhD"],
            fields_of_study=["Engineering", "Computer Science", "Electrical Engineering"],
            skills_required=["Technical Writing", "Research", "Problem Solving"],
            tags=["engineering", "stem", "professional"],
        ),
        Opportunity(
            id="seed_010",
            title="DACA Scholars Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="TheDream.US",
            amount="$14,500/year",
            deadline=date(2026, 2, 28),
            url="https://www.thedream.us/scholarships",
            description="Scholarship for DACA and undocumented students pursuing higher education",
            requirements=["DACA or TPS recipient", "High school graduate", "Financial need"],
            citizenship_requirements=["DACA"],
            gpa_requirement=2.5,
            degree_levels=["Bachelor"],
            fields_of_study=["All fields"],
            skills_required=["Community Service", "Leadership"],
            tags=["daca", "undocumented", "financial_need", "access"],
        ),
        Opportunity(
            id="seed_011",
            title="AMA Medical Student Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Medical Association",
            amount="$5,000",
            deadline=date(2026, 6, 1),
            url="https://www.ama-assn.org/scholarships",
            description='Scholarship for pre-medical and medical students demonstrating leadership in healthcare',
            requirements=['Pre-med or medical student', 'Minimum 3.0 GPA', 'Healthcare volunteer experience'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Pre-Medicine', 'Medicine', 'Biology', 'Health Sciences', 'Public Health'],
            skills_required=['Patient Care', 'Research', 'Leadership', 'Community Service'],
            tags=['healthcare', 'pre-med', 'medical'],
        ),
        Opportunity(
            id="seed_012",
            title="NIH Undergraduate Scholarship Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Institutes of Health",
            amount="$20,000/year",
            deadline=date(2026, 3, 15),
            url="https://www.training.nih.gov/programs/ugsp",
            description='Full scholarship for health-related research careers with NIH summer internship',
            requirements=['US Citizen or Permanent Resident', 'Minimum 3.5 GPA', 'Health-related major', 'Financial need'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=3.5,
            degree_levels=['Bachelor'],
            fields_of_study=['Biology', 'Chemistry', 'Psychology', 'Public Health', 'Biomedical Engineering', 'Neuroscience'],
            skills_required=['Research', 'Laboratory Skills', 'Scientific Writing'],
            tags=['healthcare', 'research', 'full_ride', 'stem'],
        ),
        Opportunity(
            id="seed_013",
            title="Stanford Medicine SUMR Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Stanford School of Medicine",
            amount="$6,000",
            deadline=date(2026, 2, 1),
            url="https://med.stanford.edu/sumr",
            description='Summer undergraduate research internship in biomedical sciences',
            requirements=['Undergraduate student', 'Interest in biomedical research', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['Biology', 'Medicine', 'Public Health', 'Biochemistry', 'Neuroscience'],
            skills_required=['Research', 'Laboratory Skills', 'Data Analysis'],
            tags=['healthcare', 'research', 'summer', 'prestigious'],
        ),
        Opportunity(
            id="seed_014",
            title="WHO Internship Program",
            type=OpportunityType.INTERNSHIP,
            organization="World Health Organization",
            amount="$3,000/month",
            deadline=date(2026, 4, 30),
            url="https://www.who.int/careers/internship-programme",
            description='Public health internship at WHO headquarters or regional offices',
            requirements=['Enrolled in graduate program', 'Public health or related field', 'English fluency'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Public Health', 'Epidemiology', 'Global Health', 'Health Policy', 'Medicine'],
            skills_required=['Data Analysis', 'Research', 'Communication'],
            tags=['healthcare', 'international', 'global_health'],
        ),
        Opportunity(
            id="seed_015",
            title="American Red Cross Health Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Red Cross",
            amount="$3,000",
            deadline=date(2026, 5, 15),
            url="https://www.redcross.org/scholarships",
            description='Scholarship for students pursuing healthcare careers with community service background',
            requirements=['Minimum 3.0 GPA', 'Community service hours', 'Health-related major'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Nursing', 'Public Health', 'Pre-Medicine', 'Health Administration', 'Biology'],
            skills_required=['Community Service', 'Patient Care', 'First Aid'],
            tags=['healthcare', 'community_service', 'undergraduate'],
        ),
        Opportunity(
            id="seed_016",
            title="CDC Public Health Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Centers for Disease Control and Prevention",
            amount="$5,000/month",
            deadline=date(2026, 3, 1),
            url="https://www.cdc.gov/students/internships",
            description='Public health internship at CDC working on disease prevention and health promotion',
            requirements=['US Citizen', 'Enrolled in public health or related program', 'Minimum 3.0 GPA'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Public Health', 'Epidemiology', 'Health Policy', 'Biostatistics', 'Environmental Health'],
            skills_required=['Data Analysis', 'Research', 'Public Speaking', 'Scientific Writing'],
            tags=['healthcare', 'public_health', 'government'],
        ),
        Opportunity(
            id="seed_017",
            title="Doctors Without Borders Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Médecins Sans Frontières",
            amount="$8,000",
            deadline=date(2026, 7, 1),
            url="https://www.doctorswithoutborders.org/scholarships",
            description='Scholarship for students committed to global health and humanitarian work',
            requirements=['Health-related major', 'Humanitarian experience', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Medicine', 'Public Health', 'Nursing', 'International Relations', 'Health Policy'],
            skills_required=['Community Service', 'Cultural Competency', 'Patient Care', 'Language Skills'],
            tags=['healthcare', 'global_health', 'humanitarian'],
        ),
        Opportunity(
            id="seed_018",
            title="Johnson & Johnson Nursing Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Johnson & Johnson",
            amount="$10,000",
            deadline=date(2026, 4, 15),
            url="https://www.jnj.com/scholarships",
            description='Scholarship for nursing students committed to improving patient care',
            requirements=['Enrolled in accredited nursing program', 'Minimum 3.2 GPA'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Nursing', 'Patient Care'],
            skills_required=['Patient Care', 'Clinical Skills', 'Communication'],
            tags=['healthcare', 'nursing', 'professional'],
        ),
        Opportunity(
            id="seed_019",
            title="Mayo Clinic Summer Undergraduate Research Fellowship",
            type=OpportunityType.INTERNSHIP,
            organization="Mayo Clinic",
            amount="$7,000",
            deadline=date(2026, 2, 15),
            url="https://www.mayo.edu/research/careers/summer-undergraduate-research-fellowship",
            description='Clinical and translational research fellowship at Mayo Clinic',
            requirements=['Undergraduate student', 'Pre-med or health sciences', 'Minimum 3.4 GPA'],
            gpa_requirement=3.4,
            degree_levels=['Bachelor'],
            fields_of_study=['Biology', 'Biochemistry', 'Pre-Medicine', 'Public Health', 'Psychology'],
            skills_required=['Research', 'Laboratory Skills', 'Data Analysis'],
            tags=['healthcare', 'research', 'clinical', 'prestigious'],
        ),
        Opportunity(
            id="seed_020",
            title="American Heart Association Predoctoral Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Heart Association",
            amount="$25,000",
            deadline=date(2026, 9, 1),
            url="https://professional.heart.org/fellowships",
            description='Fellowship for doctoral students conducting cardiovascular research',
            requirements=['PhD student', 'Cardiovascular research focus', 'Minimum 3.3 GPA'],
            gpa_requirement=3.3,
            degree_levels=['PhD'],
            fields_of_study=['Biology', 'Medicine', 'Biochemistry', 'Physiology', 'Public Health'],
            skills_required=['Research', 'Scientific Writing', 'Data Analysis'],
            tags=['healthcare', 'research', 'fellowship', 'phd'],
        ),
        Opportunity(
            id="seed_021",
            title="Global Health Corps Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Global Health Corps",
            amount="$30,000",
            deadline=date(2026, 1, 15),
            url="https://ghcorps.org/fellowship",
            description='One-year fellowship placing young leaders at health organizations worldwide',
            requirements=["Bachelor's degree", 'Under 30 years old', 'Commitment to global health equity'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Public Health', 'Medicine', 'Health Policy', 'International Development'],
            skills_required=['Leadership', 'Project Management', 'Data Analysis', 'Cross-cultural Communication'],
            tags=['healthcare', 'global_health', 'fellowship', 'leadership'],
        ),
        Opportunity(
            id="seed_022",
            title="Albert Schweitzer Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="The Albert Schweitzer Fellowship",
            amount="$25,000",
            deadline=date(2026, 3, 31),
            url="https://www.schweitzerfellowship.org",
            description='One-year fellowship developing service-oriented health professionals',
            requirements=['Graduate student in health field', 'Community service project proposal'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Medicine', 'Public Health', 'Nursing', 'Social Work', 'Health Policy'],
            skills_required=['Leadership', 'Community Service', 'Project Management'],
            tags=['healthcare', 'fellowship', 'community_service', 'graduate'],
        ),
        Opportunity(
            id="seed_023",
            title="NHSC Scholarship Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Health Service Corps",
            amount="Full tuition + living stipend",
            deadline=date(2026, 4, 30),
            url="https://nhsc.hrsa.gov/scholarships",
            description='Full scholarship for primary care health professionals serving in underserved communities',
            requirements=['US Citizen', 'Enrolled in primary care program', 'Commit to service in underserved area'],
            citizenship_requirements=['US Citizen'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Medicine', 'Nursing', 'Dentistry', 'Physician Assistant', 'Public Health'],
            skills_required=['Patient Care', 'Community Service', 'Leadership'],
            tags=['healthcare', 'full_ride', 'service', 'primary_care'],
        ),
        Opportunity(
            id="seed_024",
            title="HHMI EXROP Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Howard Hughes Medical Institute",
            amount="$6,500",
            deadline=date(2026, 2, 28),
            url="https://www.hhmi.org/science-education/programs/exrop",
            description='Summer research internship in biomedical sciences for underrepresented students',
            requirements=['Undergraduate from underrepresented background', 'Biology or chemistry major', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['Biology', 'Chemistry', 'Biochemistry', 'Neuroscience', 'Biophysics'],
            skills_required=['Research', 'Laboratory Skills'],
            tags=['healthcare', 'research', 'stem', 'diversity'],
        ),
        Opportunity(
            id="seed_025",
            title="Merck Research Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Merck & Co.",
            amount="$10,000",
            deadline=date(2026, 5, 31),
            url="https://www.merck.com/scholarships",
            description='Scholarship for students pursuing pharmaceutical sciences and biomedical research',
            requirements=['STEM major', 'Minimum 3.3 GPA', 'Interest in pharmaceutical industry'],
            gpa_requirement=3.3,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Chemistry', 'Biology', 'Pharmacy', 'Biochemistry', 'Pharmacology', 'Chemical Engineering'],
            skills_required=['Research', 'Laboratory Skills', 'Data Analysis'],
            tags=['healthcare', 'pharmaceutical', 'stem', 'research'],
        ),
        Opportunity(
            id="seed_026",
            title="ANS Undergraduate Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Nuclear Society",
            amount="$3,000",
            deadline=date(2026, 4, 1),
            url="https://www.ans.org/scholarships",
            description='Scholarship for students in nuclear science and engineering',
            requirements=['Nuclear science or engineering major', 'Minimum 3.0 GPA', 'ANS membership'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['Nuclear Engineering', 'Physics', 'Mechanical Engineering'],
            skills_required=['Problem Solving', 'Technical Writing'],
            tags=['stem', 'engineering', 'nuclear'],
        ),
        Opportunity(
            id="seed_027",
            title="Lockheed Martin STEM Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Lockheed Martin",
            amount="$8,000/month",
            deadline=date(2026, 10, 1),
            url="https://www.lockheedmartin.com/internships",
            description='Engineering internship in aerospace and defense systems',
            requirements=['Engineering or CS major', 'Minimum 3.2 GPA', 'US citizenship required'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Aerospace Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Computer Science', 'Systems Engineering'],
            skills_required=['CAD', 'MATLAB', 'Python', 'Problem Solving'],
            tags=['stem', 'engineering', 'defense', 'aerospace'],
        ),
        Opportunity(
            id="seed_028",
            title="NASA Internship Program",
            type=OpportunityType.INTERNSHIP,
            organization="NASA",
            amount="$7,500/month",
            deadline=date(2026, 3, 1),
            url="https://intern.nasa.gov",
            description='STEM internship at NASA centers working on space exploration projects',
            requirements=['US Citizen', 'STEM major', 'Minimum 3.0 GPA', 'Enrolled student'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Aerospace Engineering', 'Mechanical Engineering', 'Physics', 'Computer Science', 'Astronomy', 'Biology'],
            skills_required=['Python', 'MATLAB', 'Research', 'Problem Solving'],
            tags=['stem', 'engineering', 'space', 'government', 'prestigious'],
        ),
        Opportunity(
            id="seed_029",
            title="Society of Women Engineers Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Society of Women Engineers",
            amount="$10,000",
            deadline=date(2026, 5, 1),
            url="https://swe.org/scholarships",
            description='Scholarship for women pursuing engineering and technology degrees',
            requirements=['Female student', 'Engineering or CS major', 'Minimum 3.0 GPA', 'SWE membership'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Engineering', 'Computer Science', 'Engineering Technology', 'Physics'],
            skills_required=['Leadership', 'Problem Solving'],
            tags=['stem', 'engineering', 'women', 'diversity'],
        ),
        Opportunity(
            id="seed_030",
            title="Intel AI Research Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Intel Corporation",
            amount="$9,000/month",
            deadline=date(2026, 11, 15),
            url="https://www.intel.com/internships",
            description='Research internship in artificial intelligence and machine learning',
            requirements=['CS or ML major', 'Strong programming skills', 'Graduate student preferred'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Computer Science', 'Machine Learning', 'Artificial Intelligence', 'Data Science', 'Mathematics'],
            skills_required=['Python', 'PyTorch', 'TensorFlow', 'Machine Learning', 'Deep Learning', 'C++'],
            tags=['stem', 'ai', 'research', 'tech'],
        ),
        Opportunity(
            id="seed_031",
            title="Tesla Engineering Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Tesla",
            amount="$8,000/month",
            deadline=date(2026, 8, 1),
            url="https://www.tesla.com/careers/internships",
            description='Engineering internship in electric vehicle and energy technology',
            requirements=['Engineering major', 'Minimum 3.0 GPA', 'Hands-on project experience'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Mechanical Engineering', 'Electrical Engineering', 'Computer Science', 'Materials Science', 'Industrial Engineering'],
            skills_required=['CAD', 'Python', 'MATLAB', 'Problem Solving', 'Teamwork'],
            tags=['stem', 'engineering', 'automotive', 'energy'],
        ),
        Opportunity(
            id="seed_032",
            title="SpaceX Engineering Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Space Exploration Technologies",
            amount="$8,500/month",
            deadline=date(2026, 9, 15),
            url="https://www.spacex.com/careers/internships",
            description='Engineering internship working on rocket and spacecraft development',
            requirements=['Engineering major', 'Minimum 3.3 GPA', 'US citizenship required due to ITAR'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.3,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Aerospace Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Materials Science', 'Computer Science'],
            skills_required=['CAD', 'MATLAB', 'Python', 'Problem Solving'],
            tags=['stem', 'engineering', 'space', 'aerospace'],
        ),
        Opportunity(
            id="seed_033",
            title="Amazon SDE Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Amazon",
            amount="$9,500/month",
            deadline=date(2026, 10, 31),
            url="https://www.amazon.jobs/internships",
            description='Software development engineering internship building customer-facing features',
            requirements=['CS or related major', 'Strong DSA skills', 'Returning to degree program'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Software Engineering', 'Data Science', 'Electrical Engineering'],
            skills_required=['Java', 'Python', 'Algorithms', 'Data Structures', 'Problem Solving', 'System Design'],
            tags=['stem', 'tech', 'software', 'top_company'],
        ),
        Opportunity(
            id="seed_034",
            title="Goldman Sachs Engineering Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Goldman Sachs",
            amount="$9,000/month",
            deadline=date(2026, 9, 1),
            url="https://www.goldmansachs.com/careers/internships",
            description='Technology internship in financial services engineering',
            requirements=['CS, Engineering or related major', 'Minimum 3.2 GPA'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Computer Science', 'Computer Engineering', 'Mathematics', 'Physics', 'Financial Engineering'],
            skills_required=['Java', 'Python', 'SQL', 'Problem Solving'],
            tags=['stem', 'finance', 'tech', 'software'],
        ),
        Opportunity(
            id="seed_035",
            title="Apple Hardware Technology Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Apple",
            amount="$9,000/month",
            deadline=date(2026, 10, 15),
            url="https://www.apple.com/careers/internships",
            description='Hardware engineering internship working on next-generation Apple products',
            requirements=['EE or CE major', 'Minimum 3.2 GPA'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Electrical Engineering', 'Computer Engineering', 'Mechanical Engineering', 'Materials Science'],
            skills_required=['Circuit Design', 'Verilog', 'Python', 'MATLAB', 'Problem Solving'],
            tags=['stem', 'engineering', 'hardware', 'top_company'],
        ),
        Opportunity(
            id="seed_036",
            title="NVIDIA GPU Research Internship",
            type=OpportunityType.INTERNSHIP,
            organization="NVIDIA",
            amount="$10,000/month",
            deadline=date(2026, 11, 1),
            url="https://www.nvidia.com/internships",
            description='Research internship in GPU computing and AI acceleration',
            requirements=['PhD student preferred', 'GPU computing experience', 'Strong research background'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Computer Science', 'Electrical Engineering', 'Machine Learning', 'Physics'],
            skills_required=['CUDA', 'Python', 'C++', 'Deep Learning', 'Parallel Computing'],
            tags=['stem', 'ai', 'research', 'hardware'],
        ),
        Opportunity(
            id="seed_037",
            title="Boeing Engineering Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="The Boeing Company",
            amount="$7,500",
            deadline=date(2026, 6, 30),
            url="https://www.boeing.com/scholarships",
            description='Scholarship for engineering students with interest in aerospace',
            requirements=['Engineering major', 'Minimum 3.2 GPA', 'US Citizen'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Aerospace Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Systems Engineering'],
            skills_required=['CAD', 'MATLAB', 'Problem Solving'],
            tags=['stem', 'engineering', 'aerospace'],
        ),
        Opportunity(
            id="seed_038",
            title="Chevron STEM Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Chevron Corporation",
            amount="$5,000",
            deadline=date(2026, 4, 30),
            url="https://www.chevron.com/scholarships",
            description='Scholarship for underrepresented students pursuing STEM degrees',
            requirements=['STEM major', 'Minimum 3.0 GPA', 'Underrepresented background in STEM', 'US Citizen'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Engineering', 'Computer Science', 'Geology', 'Chemistry', 'Physics', 'Mathematics'],
            skills_required=['Problem Solving', 'Teamwork'],
            tags=['stem', 'diversity', 'energy'],
        ),
        Opportunity(
            id="seed_039",
            title="ASME Engineering Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Society of Mechanical Engineers",
            amount="$4,000",
            deadline=date(2026, 3, 15),
            url="https://www.asme.org/scholarships",
            description='Scholarship for mechanical engineering students demonstrating academic excellence',
            requirements=['Mechanical engineering major', 'Minimum 3.2 GPA', 'ASME student membership'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Mechanical Engineering'],
            skills_required=['CAD', 'MATLAB', 'Problem Solving'],
            tags=['stem', 'engineering', 'mechanical'],
        ),
        Opportunity(
            id="seed_040",
            title="ACM Student Research Competition",
            type=OpportunityType.SCHOLARSHIP,
            organization="Association for Computing Machinery",
            amount="$2,000",
            deadline=date(2026, 12, 1),
            url="https://src.acm.org",
            description='Award for outstanding undergraduate and graduate student research in computing',
            requirements=['ACM member', 'Original CS research project', 'Student status'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Software Engineering', 'Data Science', 'Artificial Intelligence'],
            skills_required=['Research', 'Technical Writing', 'Public Speaking'],
            tags=['stem', 'computing', 'research', 'competition'],
        ),
        Opportunity(
            id="seed_041",
            title="Goldman Sachs Diversity Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Goldman Sachs",
            amount="$15,000",
            deadline=date(2026, 6, 15),
            url="https://www.goldmansachs.com/scholarships",
            description='Scholarship for diverse students pursuing careers in financial services',
            requirements=['Underrepresented background in finance', 'Business or STEM major', 'Minimum 3.2 GPA'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Business', 'Finance', 'Economics', 'Computer Science', 'Mathematics'],
            skills_required=['Leadership', 'Problem Solving', 'Communication'],
            tags=['business', 'finance', 'diversity'],
        ),
        Opportunity(
            id="seed_042",
            title="McKinsey Young Leaders Internship",
            type=OpportunityType.INTERNSHIP,
            organization="McKinsey & Company",
            amount="$7,000/month",
            deadline=date(2026, 8, 15),
            url="https://www.mckinsey.com/internships",
            description='Summer internship for undergraduate students interested in management consulting',
            requirements=['Undergraduate student', 'Strong analytical skills', 'Leadership experience'],
            degree_levels=['Bachelor'],
            fields_of_study=['Business', 'Economics', 'Engineering', 'Mathematics', 'Political Science'],
            skills_required=['Data Analysis', 'Problem Solving', 'Communication', 'Leadership'],
            tags=['business', 'consulting', 'leadership'],
        ),
        Opportunity(
            id="seed_043",
            title="Deloitte Audit Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Deloitte",
            amount="$6,500/month",
            deadline=date(2026, 9, 1),
            url="https://www.deloitte.com/internships",
            description='Audit and assurance internship at one of the Big Four accounting firms',
            requirements=['Accounting or finance major', 'Minimum 3.2 GPA', 'CPA track preferred'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Accounting', 'Finance', 'Economics', 'Business'],
            skills_required=['Data Analysis', 'Excel', 'Communication', 'Attention to Detail'],
            tags=['business', 'accounting', 'finance'],
        ),
        Opportunity(
            id="seed_044",
            title="National YoungArts Foundation Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="YoungArts",
            amount="$10,000",
            deadline=date(2026, 10, 15),
            url="https://youngarts.org/apply",
            description='Award for emerging artists in visual, literary, and performing arts',
            requirements=['Artistic portfolio submission', 'Age 15-18 or grades 10-12'],
            degree_levels=['High School'],
            fields_of_study=['Art', 'Music', 'Theatre', 'Dance', 'Creative Writing', 'Film'],
            skills_required=['Artistic Excellence', 'Creativity'],
            tags=['arts', 'creative', 'undergraduate'],
        ),
        Opportunity(
            id="seed_045",
            title="AHA Fellowship in History",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Historical Association",
            amount="$3,000",
            deadline=date(2026, 5, 1),
            url="https://www.historians.org/fellowships",
            description='Research fellowship for history students conducting original archival research',
            requirements=['History major or related', 'Research proposal', 'Minimum 3.3 GPA'],
            gpa_requirement=3.3,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['History', 'Political Science', 'International Relations', 'Anthropology'],
            skills_required=['Research', 'Writing', 'Archival Research'],
            tags=['humanities', 'research', 'fellowship', 'history'],
        ),
        Opportunity(
            id="seed_046",
            title="Columbia Journalism Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Columbia Journalism School",
            amount="$5,000/month",
            deadline=date(2026, 4, 1),
            url="https://www.journalism.columbia.edu/internships",
            description='Investigative journalism internship with professional journalists',
            requirements=['Journalism or communications major', 'Writing samples required', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Journalism', 'Communications', 'English', 'Political Science'],
            skills_required=['Writing', 'Research', 'Interviewing', 'Multimedia'],
            tags=['media', 'journalism', 'communications'],
        ),
        Opportunity(
            id="seed_047",
            title="ACLU Legal Internship",
            type=OpportunityType.INTERNSHIP,
            organization="American Civil Liberties Union",
            amount="$6,000/month",
            deadline=date(2026, 3, 15),
            url="https://www.aclu.org/internships",
            description='Legal internship working on civil rights and civil liberties cases',
            requirements=['Law student or pre-law undergraduate', 'Commitment to civil rights'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Pre-Law', 'Political Science', 'Criminal Justice', 'Sociology', 'Law'],
            skills_required=['Research', 'Writing', 'Critical Thinking', 'Public Speaking'],
            tags=['law', 'civil_rights', 'public_policy'],
        ),
        Opportunity(
            id="seed_048",
            title="Economics Scholars Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Economic Association",
            amount="$5,000",
            deadline=date(2026, 6, 1),
            url="https://www.aeaweb.org/scholarships",
            description='Scholarship for economics students from underrepresented backgrounds',
            requirements=['Economics major', 'Minimum 3.2 GPA', 'Underrepresented in economics'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Economics', 'Mathematics', 'Statistics', 'Public Policy'],
            skills_required=['Data Analysis', 'Problem Solving', 'Writing'],
            tags=['economics', 'social_science', 'diversity'],
        ),
        Opportunity(
            id="seed_049",
            title="Teach For America Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Teach For America",
            amount="$30,000",
            deadline=date(2026, 5, 1),
            url="https://www.teachforamerica.org/fellowship",
            description='Two-year teaching fellowship in underserved communities across America',
            requirements=["Bachelor's degree", 'US Citizen or Permanent Resident', 'Minimum 2.5 GPA'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Communication', 'Problem Solving', 'Community Service'],
            tags=['education', 'fellowship', 'service', 'leadership'],
        ),
        Opportunity(
            id="seed_050",
            title="Rhodes Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Rhodes Trust",
            amount="Full tuition + living stipend",
            deadline=date(2026, 10, 1),
            url="https://www.rhodeshouse.ox.ac.uk/scholarships",
            description='Fully-funded postgraduate study at Oxford University for exceptional students worldwide',
            requirements=["Bachelor's degree", 'Age 18-24', 'Exceptional academic record', 'Leadership and character'],
            gpa_requirement=3.7,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Research', 'Public Speaking', 'Community Service'],
            tags=['prestigious', 'full_ride', 'international', 'oxford', 'leadership'],
        ),
        Opportunity(
            id="seed_051",
            title="AAUW International Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Association of University Women",
            amount="$20,000",
            deadline=date(2026, 11, 15),
            url="https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international",
            description='Fellowship for women who are not US citizens or permanent residents pursuing graduate study in the US',
            requirements=['Female', 'Non-US citizen', "Hold bachelor's degree", 'Apply to US graduate program'],
            citizenship_requirements=['International'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Research', 'Academic Excellence'],
            tags=['international', 'women', 'fellowship', 'graduate'],
        ),
        Opportunity(
            id="seed_052",
            title="Joint Japan/World Bank Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="World Bank Group",
            amount="Full tuition + living expenses",
            deadline=date(2026, 3, 31),
            url="https://www.worldbank.org/en/programs/scholarships",
            description='Full scholarship for students from World Bank member developing countries',
            requirements=['National of WBG developing country', "Bachelor's degree", 'Admitted to partner university program', 'Return to home country'],
            citizenship_requirements=['International'],
            degree_levels=['Master'],
            fields_of_study=['Economic Policy', 'Public Health', 'Education', 'Agriculture', 'Infrastructure', 'Governance'],
            skills_required=['Leadership', 'Research', 'Policy Analysis'],
            tags=['international', 'full_ride', 'development', 'graduate'],
        ),
        Opportunity(
            id="seed_053",
            title="Aga Khan Foundation International Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Aga Khan Foundation",
            amount="Full tuition + living expenses",
            deadline=date(2026, 3, 15),
            url="https://www.akdn.org/agakhan-foundation/scholarships",
            description='Full scholarship for outstanding students from developing countries with no other means of financing',
            requirements=['National of specific developing countries', "Bachelor's degree", 'Financial need', 'Admission to reputable university'],
            citizenship_requirements=['International'],
            gpa_requirement=3.3,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service', 'Academic Excellence'],
            tags=['international', 'full_ride', 'financial_need', 'graduate'],
        ),
        Opportunity(
            id="seed_054",
            title="Onsi Sawiris Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Sawiris Foundation",
            amount="Full tuition + living stipend",
            deadline=date(2026, 7, 15),
            url="https://www.sawirisfoundation.org/scholarships",
            description='Full scholarship for Egyptian students to pursue graduate studies abroad',
            requirements=['Egyptian national', "Bachelor's degree", 'Minimum 3.2 GPA'],
            citizenship_requirements=['International'],
            gpa_requirement=3.2,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Engineering', 'Computer Science', 'Business', 'Economics', 'Public Policy', 'Environmental Science'],
            skills_required=['Academic Excellence', 'Leadership'],
            tags=['international', 'full_ride', 'egypt', 'graduate'],
        ),
        Opportunity(
            id="seed_055",
            title="Vietnamese Education Foundation Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Vietnam Education Foundation",
            amount="Full tuition + living stipend",
            deadline=date(2026, 5, 31),
            url="https://www.vef.gov/fellowships",
            description='Fellowship for Vietnamese students to pursue graduate study in the US',
            requirements=['Vietnamese citizen', "Bachelor's degree from Vietnamese university", 'Minimum 3.5 GPA'],
            citizenship_requirements=['International'],
            gpa_requirement=3.5,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Science', 'Engineering', 'Mathematics', 'Technology'],
            skills_required=['Research', 'Academic Excellence'],
            tags=['international', 'full_ride', 'vietnam', 'stem'],
        ),
        Opportunity(
            id="seed_056",
            title="CSC Chinese Government Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="China Scholarship Council",
            amount="Full tuition + living allowance",
            deadline=date(2026, 4, 15),
            url="https://www.csc.edu.cn/scholarships",
            description='Full scholarship for international students to study at Chinese universities',
            requirements=['Non-Chinese citizen', "Bachelor's degree", 'Age under 35'],
            citizenship_requirements=['International'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Academic Excellence'],
            tags=['international', 'full_ride', 'china', 'graduate'],
        ),
        Opportunity(
            id="seed_057",
            title="Open Society Foundations Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Open Society Foundations",
            amount="$25,000",
            deadline=date(2026, 6, 1),
            url="https://www.opensocietyfoundations.org/scholarships",
            description='Scholarship for international students from marginalized communities',
            requirements=['International student from eligible country', 'Commitment to open society', "Bachelor's degree"],
            citizenship_requirements=['International'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service', 'Research'],
            tags=['international', 'human_rights', 'social_justice'],
        ),
        Opportunity(
            id="seed_058",
            title="Rotary Peace Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Rotary International",
            amount="Full tuition + living expenses",
            deadline=date(2026, 5, 15),
            url="https://www.rotary.org/en/peace-fellowships",
            description='Fully-funded fellowship for master\'s degree in peace and conflict resolution',
            requirements=["Bachelor's degree", 'Strong commitment to peace', 'English proficiency', 'Leadership experience'],
            degree_levels=['Master'],
            fields_of_study=['Peace Studies', 'Conflict Resolution', 'International Relations', 'Public Policy', 'Human Rights'],
            skills_required=['Leadership', 'Research', 'Community Service', 'Communication'],
            tags=['international', 'fellowship', 'full_ride', 'peace', 'leadership'],
        ),
        Opportunity(
            id="seed_059",
            title="Knight-Hennessy Scholars Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Stanford University",
            amount="Full tuition + living stipend",
            deadline=date(2026, 10, 9),
            url="https://knight-hennessy.stanford.edu",
            description='Full scholarship for graduate study at Stanford University for global leaders',
            requirements=["Bachelor's degree", 'Admitted to Stanford graduate program', 'Leadership potential'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Research', 'Communication', 'Community Service'],
            tags=['international', 'full_ride', 'prestigious', 'stanford', 'leadership'],
        ),
        Opportunity(
            id="seed_060",
            title="PEO International Peace Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="PEO Sisterhood",
            amount="$12,500",
            deadline=date(2026, 12, 15),
            url="https://www.peointernational.org/peace-scholarship",
            description='Scholarship for international women to pursue graduate study in the US and Canada',
            requirements=['Female', 'International student', "Bachelor's degree", 'Full-time graduate student'],
            citizenship_requirements=['International'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Academic Excellence', 'Leadership'],
            tags=['international', 'women', 'graduate', 'peace'],
        ),
        Opportunity(
            id="seed_061",
            title="UNCF General Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="United Negro College Fund",
            amount="$10,000",
            deadline=date(2026, 4, 30),
            url="https://www.uncf.org/scholarships",
            description='Scholarship for African American students attending UNCF member colleges',
            requirements=['African American', 'Minimum 2.5 GPA', 'Financial need', 'US Citizen'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service'],
            tags=['diversity', 'african_american', 'financial_need'],
        ),
        Opportunity(
            id="seed_062",
            title="Hispanic Scholarship Fund",
            type=OpportunityType.SCHOLARSHIP,
            organization="Hispanic Scholarship Fund",
            amount="$5,000",
            deadline=date(2026, 6, 15),
            url="https://www.hsf.net/scholarships",
            description='Scholarship for Hispanic American students pursuing higher education',
            requirements=['Hispanic heritage', 'US Citizen or Permanent Resident', 'Minimum 3.0 GPA', 'Full-time enrollment'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service'],
            tags=['diversity', 'hispanic', 'latino'],
        ),
        Opportunity(
            id="seed_063",
            title="American Indian College Fund Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Indian College Fund",
            amount="$5,000",
            deadline=date(2026, 5, 31),
            url="https://www.collegefund.org/scholarships",
            description='Scholarship for Native American and Alaska Native students',
            requirements=['Native American or Alaska Native', 'Enrolled in accredited college', 'Minimum 2.0 GPA'],
            gpa_requirement=2.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['All fields'],
            skills_required=['Community Service', 'Cultural Awareness'],
            tags=['diversity', 'native_american', 'indigenous'],
        ),
        Opportunity(
            id="seed_064",
            title="APIA Scholarship Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Asian & Pacific Islander American Scholarship Fund",
            amount="$10,000",
            deadline=date(2026, 1, 15),
            url="https://www.apiasf.org/scholarships",
            description='Scholarship for Asian and Pacific Islander American students',
            requirements=['Asian or Pacific Islander heritage', 'US Citizen or Permanent Resident', 'Minimum 2.5 GPA'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service'],
            tags=['diversity', 'asian', 'pacific_islander'],
        ),
        Opportunity(
            id="seed_065",
            title="Point Foundation LGBTQ+ Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Point Foundation",
            amount="$15,000",
            deadline=date(2026, 2, 15),
            url="https://www.pointfoundation.org/scholarships",
            description='Merit-based scholarship for LGBTQ+ student leaders',
            requirements=['LGBTQ+ identity', 'Minimum 3.0 GPA', 'Leadership potential', 'US Citizen or DACA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service', 'Advocacy'],
            tags=['diversity', 'lgbtq', 'leadership'],
        ),
        Opportunity(
            id="seed_066",
            title="AAHD Frederick J. Krause Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="American Association on Health and Disability",
            amount="$2,500",
            deadline=date(2026, 5, 15),
            url="https://www.aahd.us/scholarships",
            description='Scholarship for students with disabilities pursuing health-related careers',
            requirements=['Student with disability', 'Health-related major', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Public Health', 'Medicine', 'Nursing', 'Health Administration', 'Psychology', 'Social Work'],
            skills_required=['Community Service', 'Advocacy', 'Leadership'],
            tags=['diversity', 'disability', 'healthcare'],
        ),
        Opportunity(
            id="seed_067",
            title="I'm First! Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Center for Student Opportunity",
            amount="$6,000",
            deadline=date(2026, 7, 1),
            url="https://www.imfirst.org/scholarships",
            description='Scholarship for first-generation college students',
            requirements=['First-generation college student', 'Minimum 2.8 GPA', 'US Citizen or Permanent Resident'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=2.8,
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service', 'Determination'],
            tags=['diversity', 'first_generation', 'access'],
        ),
        Opportunity(
            id="seed_068",
            title="Jackie Robinson Foundation Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Jackie Robinson Foundation",
            amount="$30,000",
            deadline=date(2026, 3, 15),
            url="https://www.jackierobinson.org/scholarships",
            description='Four-year scholarship for minority students demonstrating leadership and community service',
            requirements=['Minority student', 'US Citizen', 'Minimum 3.0 GPA', 'Leadership and community service'],
            citizenship_requirements=['US Citizen'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service', 'Determination'],
            tags=['diversity', 'minority', 'leadership', 'full_ride'],
        ),
        Opportunity(
            id="seed_069",
            title="Coca-Cola First Generation Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Coca-Cola Scholars Foundation",
            amount="$20,000",
            deadline=date(2026, 10, 31),
            url="https://www.coca-colascholars.org/firstgen",
            description='Scholarship for first-generation college students attending select partner colleges',
            requirements=['First-generation college student', 'Enrolled at partner institution', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service'],
            tags=['diversity', 'first_generation', 'access', 'undergraduate'],
        ),
        Opportunity(
            id="seed_070",
            title="Generation Google Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Google",
            amount="$10,000",
            deadline=date(2026, 4, 1),
            url="https://buildyourfuture.withgoogle.com/scholarships",
            description='Scholarship for underrepresented students pursuing computer science degrees',
            requirements=['Underrepresented in tech', 'CS or related major', 'Minimum 3.3 GPA'],
            gpa_requirement=3.3,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Software Engineering', 'Data Science', 'Computer Engineering'],
            skills_required=['Problem Solving', 'Programming', 'Leadership'],
            tags=['diversity', 'tech', 'cs', 'google'],
        ),
        Opportunity(
            id="seed_071",
            title="Ford Foundation Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="The Ford Foundation",
            amount="$25,000",
            deadline=date(2026, 12, 4),
            url="https://www.nationalacademies.org/fordfellowships",
            description='Fellowship for graduate students committed to diversity in higher education',
            requirements=['US Citizen or Permanent Resident', "PhD or Master's student", 'Commitment to diversity'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Research', 'Writing', 'Teaching'],
            tags=['fellowship', 'diversity', 'graduate', 'research'],
        ),
        Opportunity(
            id="seed_072",
            title="NSF Graduate Research Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Science Foundation",
            amount="$34,000/year + tuition",
            deadline=date(2026, 10, 15),
            url="https://www.nsfgrfp.org",
            description='Prestigious fellowship supporting outstanding graduate students in STEM fields',
            requirements=['US Citizen or Permanent Resident', 'STEM graduate student', 'Strong research record'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=3.5,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Computer Science', 'Engineering', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Psychology', 'Social Sciences'],
            skills_required=['Research', 'Scientific Writing', 'Data Analysis'],
            tags=['fellowship', 'stem', 'prestigious', 'graduate', 'research'],
        ),
        Opportunity(
            id="seed_073",
            title="Hertz Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="The Hertz Foundation",
            amount="Full tuition + $38,000/year stipend",
            deadline=date(2026, 10, 1),
            url="https://www.hertzfoundation.org/fellowship",
            description='Most prestigious fellowship for PhD study in applied STEM fields',
            requirements=['US Citizen or Permanent Resident', 'PhD applicant in applied STEM', 'Exceptional research potential'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            degree_levels=['PhD'],
            fields_of_study=['Engineering', 'Computer Science', 'Physics', 'Chemistry', 'Biology', 'Mathematics'],
            skills_required=['Research', 'Innovation', 'Problem Solving', 'Leadership'],
            tags=['fellowship', 'stem', 'prestigious', 'phd', 'full_ride'],
        ),
        Opportunity(
            id="seed_074",
            title="Paul & Daisy Soros Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Paul & Daisy Soros Fellowships for New Americans",
            amount="$90,000",
            deadline=date(2026, 11, 1),
            url="https://www.pdsoros.org",
            description='Fellowship for immigrants and children of immigrants pursuing graduate study',
            requirements=['New American (immigrant or child of)', 'Graduate student', 'Age under 30'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Research', 'Community Service'],
            tags=['fellowship', 'immigrant', 'graduate', 'prestigious'],
        ),
        Opportunity(
            id="seed_075",
            title="DAAD Research Internship",
            type=OpportunityType.INTERNSHIP,
            organization="German Academic Exchange Service",
            amount="$3,000/month",
            deadline=date(2026, 5, 31),
            url="https://www.daad.de/internships",
            description='Research internship at German universities and research institutes',
            requirements=['Enrolled student', 'Research proposal', 'German language not required'],
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Engineering', 'Computer Science', 'Natural Sciences', 'Mathematics'],
            skills_required=['Research', 'Data Analysis', 'Laboratory Skills'],
            tags=['international', 'research', 'germany', 'stem'],
        ),
        Opportunity(
            id="seed_076",
            title="Max Planck Internship Program",
            type=OpportunityType.INTERNSHIP,
            organization="Max Planck Society",
            amount="$2,500/month",
            deadline=date(2026, 6, 30),
            url="https://www.mpg.de/internships",
            description='Research internship at world-renowned Max Planck Institutes',
            requirements=['Undergraduate or graduate student', 'Strong academic record'],
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Physics', 'Chemistry', 'Biology', 'Computer Science', 'Mathematics', 'Neuroscience'],
            skills_required=['Research', 'Data Analysis', 'Laboratory Skills'],
            tags=['international', 'research', 'germany', 'stem'],
        ),
        Opportunity(
            id="seed_077",
            title="CERN Technical Student Program",
            type=OpportunityType.INTERNSHIP,
            organization="CERN",
            amount="$5,000/month",
            deadline=date(2026, 7, 1),
            url="https://careers.cern/internships",
            description='Technical internship at the European particle physics laboratory',
            requirements=['Physics or engineering student', 'Minimum 3.5 GPA', '3+ years of study'],
            gpa_requirement=3.5,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Physics', 'Computer Science', 'Engineering', 'Mathematics', 'Data Science'],
            skills_required=['Python', 'C++', 'Data Analysis', 'Problem Solving'],
            tags=['international', 'research', 'physics', 'cern'],
        ),
        Opportunity(
            id="seed_078",
            title="Google Research Scholar Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Google",
            amount="$60,000",
            deadline=date(2026, 9, 1),
            url="https://research.google/outreach/research-scholar-program",
            description='Funding for early-career faculty and research students in computing',
            requirements=['Research focus in computing', 'Strong publication record'],
            degree_levels=['PhD'],
            fields_of_study=['Computer Science', 'Machine Learning', 'Data Science', 'Systems', 'Security', 'NLP'],
            skills_required=['Research', 'Machine Learning', 'Python', 'Publications'],
            tags=['fellowship', 'research', 'tech', 'phd', 'google'],
        ),
        Opportunity(
            id="seed_079",
            title="Microsoft Research PhD Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Microsoft Research",
            amount="$42,000",
            deadline=date(2026, 8, 1),
            url="https://www.microsoft.com/en-us/research/academic-program/phd-fellowship",
            description='Two-year fellowship for PhD students in computing research',
            requirements=['PhD student in CS or related', 'Research in computing', 'Strong academic record'],
            degree_levels=['PhD'],
            fields_of_study=['Computer Science', 'Electrical Engineering', 'Human-Computer Interaction', 'Data Science'],
            skills_required=['Research', 'Publication Record', 'Programming'],
            tags=['fellowship', 'research', 'tech', 'phd', 'microsoft'],
        ),
        Opportunity(
            id="seed_080",
            title="Meta Fellowship Program",
            type=OpportunityType.SCHOLARSHIP,
            organization="Meta",
            amount="$42,000",
            deadline=date(2026, 9, 30),
            url="https://research.facebook.com/fellowships",
            description='Fellowship for PhD students in AI, systems, and computing research',
            requirements=['PhD student', 'Research in relevant area', 'Strong publication record'],
            degree_levels=['PhD'],
            fields_of_study=['Computer Science', 'Machine Learning', 'Artificial Intelligence', 'Data Science', 'Systems'],
            skills_required=['Research', 'Machine Learning', 'Python', 'Publications'],
            tags=['fellowship', 'research', 'tech', 'phd', 'ai'],
        ),
        Opportunity(
            id="seed_081",
            title="Cal Grant A",
            type=OpportunityType.SCHOLARSHIP,
            organization="California Student Aid Commission",
            amount="$12,570/year",
            deadline=date(2026, 3, 2),
            url="https://www.csac.ca.gov/cal-grants",
            description='California state grant for low- and middle-income California residents',
            requirements=['California resident', 'US Citizen or eligible non-citizen', 'Financial need', 'Minimum 3.0 GPA'],
            citizenship_requirements=['US Citizen', 'Permanent Resident', 'DACA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=[],
            tags=['california', 'state', 'financial_need', 'undergraduate'],
        ),
        Opportunity(
            id="seed_082",
            title="Texas TEXAS Grant",
            type=OpportunityType.SCHOLARSHIP,
            organization="Texas Higher Education Coordinating Board",
            amount="$8,000/year",
            deadline=date(2026, 3, 1),
            url="https://www.highered.texas.gov/grants",
            description='Texas state grant for residents attending Texas public universities',
            requirements=['Texas resident', 'Financial need', 'Minimum 2.5 GPA', 'US Citizen or eligible non-citizen'],
            citizenship_requirements=['US Citizen', 'Permanent Resident'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=[],
            tags=['texas', 'state', 'financial_need', 'undergraduate'],
        ),
        Opportunity(
            id="seed_083",
            title="New York Excelsior Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="New York State HESC",
            amount="Full tuition at SUNY/CUNY",
            deadline=date(2026, 7, 15),
            url="https://www.hesc.ny.gov/excelsior",
            description='New York state scholarship covering tuition at SUNY and CUNY institutions',
            requirements=['New York resident', 'Attend SUNY/CUNY', 'Family income under $125k', 'Minimum 30 credits/year'],
            citizenship_requirements=['US Citizen', 'Permanent Resident', 'DACA'],
            degree_levels=['Bachelor'],
            fields_of_study=['All fields'],
            skills_required=[],
            tags=['new_york', 'state', 'full_ride', 'undergraduate'],
        ),
        Opportunity(
            id="seed_084",
            title="Erasmus Mundus Joint Master",
            type=OpportunityType.SCHOLARSHIP,
            organization="European Commission",
            amount="€25,000/year",
            deadline=date(2026, 2, 15),
            url="https://erasmus-plus.ec.europa.eu/opportunities",
            description='Full scholarship for master\'s study at multiple European universities',
            requirements=["Bachelor's degree", 'Non-EU students eligible', 'English proficiency'],
            degree_levels=['Master'],
            fields_of_study=['All fields'],
            skills_required=['Research', 'Cross-cultural Communication', 'Language Skills'],
            tags=['international', 'europe', 'full_ride', 'graduate'],
        ),
        Opportunity(
            id="seed_085",
            title="Chevening Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="UK Foreign & Commonwealth Office",
            amount="Full tuition + living expenses",
            deadline=date(2026, 11, 1),
            url="https://www.chevening.org/scholarships",
            description='Full scholarship for one-year master\'s study at any UK university',
            requirements=['International student from eligible country', "Bachelor's degree", '2+ years work experience', 'Return to home country'],
            citizenship_requirements=['International'],
            degree_levels=['Master'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Research', 'Communication'],
            tags=['international', 'uk', 'full_ride', 'prestigious'],
        ),
        Opportunity(
            id="seed_086",
            title="Australia Awards Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Australian Department of Foreign Affairs and Trade",
            amount="Full tuition + living expenses",
            deadline=date(2026, 4, 30),
            url="https://www.dfat.gov.au/australia-awards",
            description='Full scholarship for international students from developing countries to study in Australia',
            requirements=['National of eligible developing country', "Bachelor's degree", 'Return to home country'],
            citizenship_requirements=['International'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Community Service'],
            tags=['international', 'australia', 'full_ride', 'development'],
        ),
        Opportunity(
            id="seed_087",
            title="Schwarzman Scholars",
            type=OpportunityType.SCHOLARSHIP,
            organization="Schwarzman Scholars",
            amount="Full tuition + living expenses",
            deadline=date(2026, 9, 12),
            url="https://www.schwarzmanscholars.org",
            description='One-year master\'s program at Tsinghua University for future global leaders',
            requirements=["Bachelor's degree", 'Age 18-28', 'English proficiency', 'Leadership potential'],
            degree_levels=['Master'],
            fields_of_study=['All fields'],
            skills_required=['Leadership', 'Cross-cultural Communication', 'Public Speaking'],
            tags=['international', 'china', 'full_ride', 'prestigious', 'fellowship'],
        ),
        Opportunity(
            id="seed_088",
            title="MEXT Japanese Government Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Ministry of Education, Japan",
            amount="Full tuition + living allowance",
            deadline=date(2026, 5, 15),
            url="https://www.mext.go.jp/en/scholarships",
            description='Full scholarship for international students to study at Japanese universities',
            requirements=['International student', "Bachelor's degree", 'Age under 35', 'Japanese or English proficiency'],
            citizenship_requirements=['International'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['All fields'],
            skills_required=['Language Skills', 'Academic Excellence'],
            tags=['international', 'japan', 'full_ride', 'graduate'],
        ),
        Opportunity(
            id="seed_089",
            title="Vanier Canada Graduate Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Government of Canada",
            amount="CAD 50,000/year",
            deadline=date(2026, 11, 1),
            url="https://www.vanier.gc.ca",
            description='Prestigious scholarship for PhD students at Canadian universities',
            requirements=['International or Canadian PhD applicant', 'Strong research record', 'Leadership potential'],
            degree_levels=['PhD'],
            fields_of_study=['All fields'],
            skills_required=['Research', 'Leadership', 'Academic Excellence'],
            tags=['international', 'canada', 'phd', 'prestigious', 'fellowship'],
        ),
        Opportunity(
            id="seed_090",
            title="HBKU Graduate Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Hamad Bin Khalifa University",
            amount="Full tuition + living stipend",
            deadline=date(2026, 4, 1),
            url="https://www.hbku.edu.qa/scholarships",
            description='Full scholarship for graduate study at Qatar Foundation university',
            requirements=["Bachelor's degree", 'Minimum 3.0 GPA', 'English proficiency'],
            gpa_requirement=3.0,
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Engineering', 'Computer Science', 'Public Health', 'Islamic Studies', 'Law', 'Humanities'],
            skills_required=['Research', 'Academic Excellence'],
            tags=['international', 'qatar', 'full_ride', 'graduate'],
        ),
        Opportunity(
            id="seed_091",
            title="Google Lime Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Google",
            amount="$10,000",
            deadline=date(2026, 11, 30),
            url="https://buildyourfuture.withgoogle.com/scholarships/google-lime-scholarship",
            description='Scholarship for students with disabilities pursuing computing degrees',
            requirements=['Student with disability', 'CS or related major', 'Minimum 2.5 GPA'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Computer Engineering', 'Data Science', 'Information Technology'],
            skills_required=['Problem Solving', 'Programming'],
            tags=['tech', 'diversity', 'disability', 'google'],
        ),
        Opportunity(
            id="seed_092",
            title="Women Techmakers Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Google",
            amount="$10,000",
            deadline=date(2026, 12, 1),
            url="https://www.womentechmakers.com/scholarships",
            description='Scholarship for women in computer science and related fields',
            requirements=['Woman in tech', 'CS or related major', 'Minimum 2.5 GPA'],
            gpa_requirement=2.5,
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Computer Engineering', 'Data Science', 'Information Technology', 'Design'],
            skills_required=['Problem Solving', 'Leadership', 'Programming'],
            tags=['tech', 'women', 'diversity', 'google'],
        ),
        Opportunity(
            id="seed_093",
            title="Palantir Future Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Palantir Technologies",
            amount="$7,000",
            deadline=date(2026, 4, 15),
            url="https://www.palantir.com/scholarships",
            description='Scholarship for STEM students with an entrepreneurial mindset',
            requirements=['STEM major', 'Minimum 3.2 GPA', 'Innovative project or idea'],
            gpa_requirement=3.2,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Computer Science', 'Engineering', 'Mathematics', 'Physics', 'Data Science'],
            skills_required=['Problem Solving', 'Innovation', 'Programming'],
            tags=['tech', 'stem', 'innovation'],
        ),
        Opportunity(
            id="seed_094",
            title="Adobe Creative Residency",
            type=OpportunityType.INTERNSHIP,
            organization="Adobe Inc.",
            amount="$6,000/month",
            deadline=date(2026, 5, 1),
            url="https://www.adobe.com/careers/internships",
            description='Creative internship for designers, photographers, and visual artists',
            requirements=['Design or arts major', 'Portfolio required', 'Adobe software proficiency'],
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Design', 'Art', 'Photography', 'Film', 'Animation', 'Visual Arts'],
            skills_required=['Adobe Creative Suite', 'Design', 'Creativity', 'Portfolio'],
            tags=['creative', 'design', 'tech'],
        ),
        Opportunity(
            id="seed_095",
            title="Disney Imagineering Internship",
            type=OpportunityType.INTERNSHIP,
            organization="Walt Disney Company",
            amount="$7,000/month",
            deadline=date(2026, 8, 31),
            url="https://disneyimaginations.com/internships",
            description='Internship designing and building Disney theme park experiences',
            requirements=['Engineering, design, or arts major', 'Creative portfolio', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Mechanical Engineering', 'Electrical Engineering', 'Architecture', 'Design', 'Computer Science', 'Theatre'],
            skills_required=['CAD', 'Creativity', 'Problem Solving', 'Teamwork'],
            tags=['creative', 'engineering', 'entertainment'],
        ),
        Opportunity(
            id="seed_096",
            title="National Geographic Young Explorer Grant",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Geographic Society",
            amount="$5,000",
            deadline=date(2026, 9, 30),
            url="https://www.nationalgeographic.org/grants",
            description='Grant for students conducting exploratory field research worldwide',
            requirements=['Research proposal', 'Fieldwork focus', 'Age 18-25'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Biology', 'Geography', 'Anthropology', 'Environmental Science', 'Photography', 'Oceanography'],
            skills_required=['Research', 'Fieldwork', 'Photography', 'Writing'],
            tags=['research', 'environment', 'exploration', 'fieldwork'],
        ),
        Opportunity(
            id="seed_097",
            title="Stripe Press Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="Stripe",
            amount="$15,000",
            deadline=date(2026, 6, 1),
            url="https://stripe.com/scholarships",
            description='Scholarship for students building digital infrastructure and online businesses',
            requirements=['CS or business major', 'Building software or business project', 'Minimum 3.0 GPA'],
            gpa_requirement=3.0,
            degree_levels=['Bachelor', 'Master'],
            fields_of_study=['Computer Science', 'Business', 'Economics', 'Design'],
            skills_required=['Programming', 'Product Development', 'Entrepreneurship'],
            tags=['tech', 'entrepreneurship', 'startup'],
        ),
        Opportunity(
            id="seed_098",
            title="Google Summer of Code",
            type=OpportunityType.INTERNSHIP,
            organization="Google",
            amount="$7,500",
            deadline=date(2026, 4, 15),
            url="https://summerofcode.withgoogle.com",
            description='Remote open-source software development internship',
            requirements=['Student or recent graduate', 'Programming experience', 'Open source interest'],
            degree_levels=['Bachelor', 'Master', 'PhD'],
            fields_of_study=['Computer Science', 'Software Engineering', 'Data Science'],
            skills_required=['Programming', 'Git', 'Open Source', 'Problem Solving'],
            tags=['tech', 'open_source', 'software', 'remote'],
        ),
        Opportunity(
            id="seed_099",
            title="CodePath Tech Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="CodePath.org",
            amount="Free training + stipend",
            deadline=date(2026, 8, 1),
            url="https://www.codepath.org/fellowships",
            description='Free industry-aligned software engineering training for underrepresented students',
            requirements=['Underrepresented in tech', 'CS major', 'US college student'],
            degree_levels=['Bachelor'],
            fields_of_study=['Computer Science', 'Software Engineering', 'Data Science', 'Computer Engineering'],
            skills_required=['Problem Solving', 'Teamwork', 'Communication'],
            tags=['tech', 'fellowship', 'diversity', 'software'],
        ),
        Opportunity(
            id="seed_100",
            title="UNESCO/ISEDC Fellowship",
            type=OpportunityType.SCHOLARSHIP,
            organization="UNESCO",
            amount="$10,000",
            deadline=date(2026, 6, 15),
            url="https://www.unesco.org/fellowships",
            description='Fellowship for students from developing countries in sustainable energy',
            requirements=['International student from developing country', 'Engineering or energy-related major', "Bachelor's degree"],
            citizenship_requirements=['International'],
            degree_levels=['Master', 'PhD'],
            fields_of_study=['Environmental Engineering', 'Energy', 'Sustainable Development', 'Mechanical Engineering', 'Electrical Engineering'],
            skills_required=['Research', 'Data Analysis', 'Technical Writing'],
            tags=['international', 'sustainability', 'energy', 'fellowship'],
        ),
        # Canonical Borderline demo opportunity. Designed so the demo profile
        # (Maya Chen: international, undergraduate, Pre-Med, GPA 3.7) satisfies every
        # hard rule (citizenship open, Bachelor, Pre-Med field) and misses ONLY the
        # 3.8 GPA floor by 0.1 — inside the 0.2 tolerance — yielding ⚠️ Borderline.
        Opportunity(
            id="seed_101",
            title="Rural Health Pre-Med Excellence Scholarship",
            type=OpportunityType.SCHOLARSHIP,
            organization="National Rural Health Foundation",
            amount="$12,000",
            deadline=date(2026, 3, 1),
            url="https://www.ruralhealthfoundation.org/premed-scholarship",
            description=(
                "Merit scholarship for pre-medical and health sciences undergraduates — "
                "including international students — committed to careers in rural and "
                "underserved community medicine. Supports students working to reduce "
                "healthcare disparities through public health, research, and patient care."
            ),
            requirements=[
                "Open to international and domestic undergraduate students",
                "Pre-med or health-related major",
                "Minimum 3.8 GPA",
                "Demonstrated commitment to rural or underserved healthcare",
            ],
            citizenship_requirements=[],  # open to all nationalities, incl. international
            gpa_requirement=3.8,
            degree_levels=["Bachelor"],
            fields_of_study=["Pre-Med", "Pre-Medicine", "Medicine", "Public Health", "Biology", "Health Sciences", "Nursing"],
            skills_required=["Research", "Patient Care", "Public Health", "Community Service"],
            tags=["healthcare", "pre-med", "rural_health", "international", "borderline_demo"],
        ),
    ]

    OPPORTUNITIES_BY_ID = {o.id: o for o in SEED_OPPORTUNITIES}

    def search_by_profile(self, profile) -> list[Opportunity]:
        matches = []
        for opp in self.SEED_OPPORTUNITIES:
            score = 0
            if opp.fields_of_study:
                major_lower = profile.major.lower()
                for f in opp.fields_of_study:
                    if major_lower in f.lower() or f.lower() in major_lower:
                        score += 3
                        break
            if opp.degree_levels and profile.degree_level:
                if any(d.lower() in profile.degree_level.lower() or profile.degree_level.lower() in d.lower() for d in opp.degree_levels):
                    score += 2
            if profile.skills and opp.skills_required:
                profile_skills = set(s.lower() for s in profile.skills)
                req_skills = set(s.lower() for s in opp.skills_required)
                overlap = profile_skills & req_skills
                score += len(overlap) * 1.5

            if score >= 2:
                matches.append(opp)

        return matches or self.SEED_OPPORTUNITIES[:5]

    def get_by_id(self, opp_id: str) -> Optional[Opportunity]:
        return self.OPPORTUNITIES_BY_ID.get(opp_id)

    def search_by_query(self, query: str) -> list[Opportunity]:
        query_lower = query.lower()
        results = []
        for opp in self.SEED_OPPORTUNITIES:
            if (query_lower in opp.title.lower()
                    or query_lower in opp.organization.lower()
                    or query_lower in opp.description.lower()
                    or any(query_lower in t.lower() for t in opp.tags)):
                results.append(opp)
        return results

    def get_all(self) -> list[Opportunity]:
        return self.SEED_OPPORTUNITIES
